#================================================================================
#
# Copyright (C) 2024 Institute of Theoretical Astrophysics, University of Oslo.
#
# This file is part of Commander3.
#
# Commander3 is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Commander3 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Commander3. If not, see <https://www.gnu.org/licenses/>.
#
#================================================================================
import h5py
import numpy as np
import commander_tools.tod_tools.commander_instrument as inst


class spider(object):

    freqs = [90, 150]
    nside = 512
    npsi = 4096

    huffman = ['huffman', {'dictNum':1}]
    psiDigitize = ['digitize', {'min':0, 'max':2*np.pi,'nbins':npsi, 'offset':1}] # Will give values from 1 to npsi, inclusive.
 

    @staticmethod
    def instrument_filename(version):
        return 'spider_instrument_v' + str(version) + '.h5'

    @staticmethod
    def detlist_name(freq):
        return 'detlist_spider_'+str(freq)+'.txt'


    @staticmethod 
    def verify_instrument_file(outDir, version):
        f = inst.commander_instrument(outDir, spider.instrument_filename(version), version, 'r')

        if version <= 3:
            print('This instrument file was generated by code that has now been lost, use at your own risk')

        if version == 4:
            #do something here
            pass

        if version > 4:
            raise ValueError('Version ' + str(version) + ' of the spider instrument file has yet to be defined') 
