	Integer*4 Function FGA_LIST_LIMFLAGS ( WRITE_LUN, LIMFLAGS,
	1				       LIMFLAGS_FILE, CLINE, NREC)

C-----------------------------------------------------------------------
C
C	PROGRAM NAME:
C	  FGA_LIST_LIMFLAGS
C
C	PROGRAM DESCRIPTION:
C	  The program will get a formatted listing of FIRAS LIMFLAGS
C         record.
C
C	CALLING SEQUENCE:
C	  CALL FGA_LIST_LIMFLAGS (WRITE_LUN, LIMFLAGS,LIMFLAGS_FILE, NREC)
C
C	INPUT PARAMETERS:
C	  WRITE_LUN		I*4	Logical unit number for a list file;
C					if not supplied assume 6.  Assume the
C					calling routine has opened this list file.
C	  LIMFLAGS		RECORD	FIRAS LIMFLAGS RECORD
C	  NREC			I*2	Count of the number of records in this run
C	  CLINE			C*80	Comment line to identify the list file
C
C	OUTPUT PARAMETERS:
C	  NONE
C
C	INPUT FILES:
C	  NONE
C
C	OUTPUT FILES:
C	  Listing file or FOR006
C
C	INCLUDE FILES USED:
C	  FUT_QUALFLAGS_NAMES.TXT
C
C	SUBROUTINES CALLED:
C	  BINARY_TO_GMT
C
C-----------------------------------------------------------------------
C Changes:
C
C       SPR 4750.  Oct 10, 1989, Q. Chung Modify to dump LIMFLAGS data
C		   quality flag in bits.
C	SPR 6159.  May 25, 1990, R. Kummerer, STX@GSFC, Version 6.1.
C		   Clean up reference data set lists.
C       SPR 8372   May 14, l991, N. Gonzales, STX
C                  Replaced FLG_MOON field with FLG_NO_ATTITUDE
C	SPR 9162   Oct 15, 1991, S. Alexander, STX
C		   Fix dumps of micro status and ipdu current status.
C-----------------------------------------------------------------------

	IMPLICIT	NONE

	INCLUDE        '(FUT_QUALFLAG_NAMES)'

	INTEGER		*2	NREC
	INTEGER		*4	WRITE_LUN
	INTEGER		*4	STATUS

	CHARACTER	*14	GMT_START,GMT_STOP,GMT
	
        INTEGER         *4      MJR_FRAME
        INTEGER         *4      SUCCESS/1/,ERROR/2/
	INTEGER		*2	I
	INTEGER		*2	J
	INTEGER		*2	K
	INTEGER		*2	L

        Integer         *2      QUALFLAGS

        CHARACTER       *14     TEXT(2)/'RED LIMIT: ','YELLOW LIMIT: '/
	CHARACTER       *64     LIMFLAGS_FILE
	CHARACTER       *80	CLINE
        CHARACTER               MICRO_ST(2,8)
        CHARACTER               GRTRED_ST(16,8),GRTYEL_ST(16,8)
        CHARACTER               FLG_ATT_ALT_RED_BITS(8)
        CHARACTER               FLG_ATT_ALT_YEL_BITS(8)
        CHARACTER               FLG_TC_RED_BITS(8)
        CHARACTER               FLG_TC_YEL_BITS(8)
        CHARACTER               FLG_STCHG_MJ_ST_BITS(4,8)
        CHARACTER       *1      LINE(90)/90*'-'/
        LOGICAL         *1      FIRST/.TRUE./

	DICTIONARY	'FEX_LIMFLAGS'
	RECORD /FEX_LIMFLAGS/ LIMFLAGS

	EXTERNAL		FGA_WRITE_ERR

C
C Begin the dump.
C
	IF (WRITE_LUN .EQ. 0) WRITE_LUN = 6

        IF (FIRST) THEN
	  WRITE (WRITE_LUN, 6000, IOSTAT=STATUS) LIMFLAGS_FILE,CLINE,LINE
          L = 0
          FIRST = .FALSE.
        ENDIF
6000	FORMAT ( / 1X, 'FEX_LIMFLAGS FILE : ',A/,X,A80/,90A/)

	IF (STATUS .NE. 0) THEN
	  CALL LIB$SIGNAL ( FGA_WRITE_ERR, %VAL(1), %VAL(STATUS) )
	END IF
C
C Cobetrieve standard header.
C
        L = L + 1
	WRITE (WRITE_LUN, 6001, IOSTAT=STATUS) TEXT(L),
	1			(LIMFLAGS.CT_HEAD.GMT(I:I), I=1,14),
	1			LIMFLAGS.CT_HEAD.TIME(2),
	1			LIMFLAGS.CT_HEAD.TIME(1),
	1			LIMFLAGS.CT_HEAD.SPACE_TIME,
	1			LIMFLAGS.CT_HEAD.MJR_FRM_NO,
	1			LIMFLAGS.CT_HEAD.ORBIT,
	1			LIMFLAGS.CT_HEAD.DATASET_ID,
	1                       LINE

6001	FORMAT (/' Processed Time (in 3 Formats) For ',A /,
	1	' <GMT> : ', 2A1, '-', 3A1, '-', 3(2A1, '-'), 3A1, 7X,
	1	' <Binary> : ', Z8.8, 1X, Z8.8, 7X,
	1	' <PB5> : ',  6(Z2.2, 1X) /
	1	' Major Frame Number : ', I6, 8x, 
	1	' Orbit number : ', I6, 14x,
	1       ' Data Set ID : ',I6,/,130A/)

	IF (STATUS .NE. 0) THEN
	  CALL LIB$SIGNAL ( FGA_WRITE_ERR, %VAL(1), %VAL(STATUS) )
	END IF

C DECODE MICRO STATUS BITS

	DO I = 1,2
           QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_MICRO(I)
           DO K = 0,7
              MICRO_ST(I,8-K) = '0'
              IF(BTEST(QUALFLAGS,K)) MICRO_ST(I,8-K) = '1'
           ENDDO
        ENDDO

C DECODE FLG_ATT_ALT_RED BITS

	QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_ATT_ALT_RED
	DO K = 0,7
           FLG_ATT_ALT_RED_BITS(8-K) = '0'
           IF (BTEST(QUALFLAGS,K)) FLG_ATT_ALT_RED_BITS(8-K) = '1'
        ENDDO 

C DECODE FLG_ATT_ALT_YEL BITS

	QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_ATT_ALT_YEL
	DO K = 0,7
           FLG_ATT_ALT_YEL_BITS(8-K) = '0'
           IF (BTEST(QUALFLAGS,K)) FLG_ATT_ALT_YEL_BITS(8-K) = '1'
        ENDDO

C DECODE GRT RED STATUS BITS 

        DO I = 1,16
           QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_GRTRED_ST(I)
           DO K = 0,7
              GRTRED_ST(I,8-K) = '0'
              IF (BTEST(QUALFLAGS,K)) GRTRED_ST(I,8-K) = '1'
           ENDDO
        ENDDO           

C DECODE GRT YELLOW STATUS BITS

        DO I = 1,16
           QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_GRTYEL_ST(I)
           DO K = 0,7
              GRTYEL_ST(I,8-K) = '0'
              IF (BTEST(QUALFLAGS,K)) GRTYEL_ST(I,8-K) = '1'
           ENDDO
        ENDDO           

C DECODE TEMPERATURE CONTROLLER RED STATUS BITS

	QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_TC_RED
	DO K = 0,7
           FLG_TC_RED_BITS(8-K) = '0'
           IF (BTEST(QUALFLAGS,K)) FLG_TC_RED_BITS(8-K) = '1'
        ENDDO

C DECODE TEMPERATURE CONTROLLER'S YELLOW STATUS BITS

	QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_TC_YEL
	DO K = 0,7
           FLG_TC_YEL_BITS(8-K) = '0'
           IF (BTEST(QUALFLAGS,K)) FLG_TC_YEL_BITS(8-K) = '1'
        ENDDO

  	DO I = 1,4
           QUALFLAGS = LIMFLAGS.LIM_FLAGS.FLG_STCHG_MJ_ST(I)
           DO K = 0,7
              FLG_STCHG_MJ_ST_BITS(I,8-K) = '0'
              IF (BTEST(QUALFLAGS,K)) FLG_STCHG_MJ_ST_BITS(I,8-K) = '1'
           ENDDO
        ENDDO

C FORMAT DUMP OUT THE LIM_FLAGS RECORD

	WRITE (WRITE_LUN,6020) Text(L),
	1 QUALFLAG_NAMES(1),LIMFLAGS.LIM_FLAGS.FLG_BADSCI,
	1 QUALFLAG_NAMES(2),LIMFLAGS.LIM_FLAGS.FLG_BADHKP,
	1 QUALFLAG_NAMES(3),LIMFLAGS.LIM_FLAGS.FLG_CAL,
	1 QUALFLAG_NAMES(4),((MICRO_ST(L,J),J=1,8),L=1,2),   
	1 QUALFLAG_NAMES(6),FLG_ATT_ALT_RED_BITS,
	1 QUALFLAG_NAMES(7),FLG_ATT_ALT_YEL_BITS,
	1 QUALFLAG_NAMES(8),LIMFLAGS.LIM_FLAGS.FLG_GLITCH_CT,
	1 QUALFLAG_NAMES(9),LIMFLAGS.LIM_FLAGS.FLG_SATURATE,
	1 QUALFLAG_NAMES(10),LIMFLAGS.LIM_FLAGS.FLG_CKSM_ERR_ST,
	1 QUALFLAG_NAMES(11),((GRTRED_ST(I,J),J=1,8),I=1,16),
	1 QUALFLAG_NAMES(19),((GRTYEL_ST(I,J),J=1,8),I=1,16),
	1 QUALFLAG_NAMES(27),FLG_TC_RED_BITS,
	1 QUALFLAG_NAMES(28),FLG_TC_YEL_BITS,
	1 QUALFLAG_NAMES(29),(LIMFLAGS.LIM_FLAGS.FLG_IPDU_TMP(I),I=1,4),
	1 QUALFLAG_NAMES(31),(LIMFLAGS.LIM_FLAGS.FLG_CHAN_TMP_ST(I),I=1,8),
	1 QUALFLAG_NAMES(32),(LIMFLAGS.LIM_FLAGS.FLG_DBOX_TMP(I),I=1,2),
	1 QUALFLAG_NAMES(34),(LIMFLAGS.LIM_FLAGS.FLG_STMON_TMP(I),I=1,4),
	1 QUALFLAG_NAMES(35),(LIMFLAGS.LIM_FLAGS.FLG_CHPA_TMP(I),I=1,2),
	1 QUALFLAG_NAMES(36),(LIMFLAGS.LIM_FLAGS.FLG_OPPA_TMP(I),I=1,2),
	1 QUALFLAG_NAMES(37),(LIMFLAGS.LIM_FLAGS.FLG_HS_HEAT_A(I),I=1,2),
	1 QUALFLAG_NAMES(38),(LIMFLAGS.LIM_FLAGS.FLG_HS_HEAT_B(I),I=1,2),
	1 QUALFLAG_NAMES(39),(LIMFLAGS.LIM_FLAGS.FLG_MTMCAL_MTR(I),I=1,4),
	1 QUALFLAG_NAMES(41),(LIMFLAGS.LIM_FLAGS.FLG_BOL_VOL_ST(I),I=1,8),
	1 QUALFLAG_NAMES(42),(LIMFLAGS.LIM_FLAGS.FLG_IPDU_VOL_ST(I),I=1,40),
	1 QUALFLAG_NAMES(52),(LIMFLAGS.LIM_FLAGS.FLG_IPDU_CUR_ST(I),I=1,12),
	1 QUALFLAG_NAMES(58),((FLG_STCHG_MJ_ST_BITS(I,J),J=1,8),I=1,4)

        QUALFLAG_NAMES(86) = 'FLG_SPARES     '

	WRITE(WRITE_LUN,6021)
	1 QUALFLAG_NAMES(62),(LIMFLAGS.LIM_FLAGS.FLG_DIRBE_ST(I),I=1,8),
	1 QUALFLAG_NAMES(70),(LIMFLAGS.LIM_FLAGS.FLG_DMR_ST(I),I=1,6),
	1 QUALFLAG_NAMES(76),(LIMFLAGS.LIM_FLAGS.FLG_SPACECR_ST(I),I=1,8),
	1 QUALFLAG_NAMES(84),(LIMFLAGS.LIM_FLAGS.FLG_ACLMAC_TMP(I),I=1,2),
	1 QUALFLAG_NAMES(85),(LIMFLAGS.LIM_FLAGS.FLG_DCLMAC_TMP(I),I=1,2),
	1 QUALFLAG_NAMES(86),(LIMFLAGS.LIM_FLAGS.FLG_SPARES(I),I=1,74),
	1 QUALFLAG_NAMES(108),(LIMFLAGS.LIM_FLAGS.FLG_NO_ATTITUDE(I),I=1,2),
	1 QUALFLAG_NAMES(109),(LIMFLAGS.LIM_FLAGS.FLG_ATT_SUM(I),I=1,2),
	1 QUALFLAG_NAMES(110),(LIMFLAGS.LIM_FLAGS.FLG_SUMMARY(I),I=1,2)

 6020	FORMAT (/1X,'FEX_LIMFLAGS Data Record For ',A,//,
	1	1X,A,2X,I3/,1X,A,2X,I3/,1X,A,2X,I3/,1X,A,2X,8A,2X,8A/,
	1	1X,A,2X,8A/,1X,A,2X,8A/,3(1x,a,2x,I3/)/,
	1        1x,A,8(8A,5X)/,16X,8(8A,5X)/,1x,A,8(8A,5X)/,
	2        16X,8(8A,5X)/,1X,A,2X,8A/,1X,A,2X,8A/,1X,
	3        A,4(I3,2X)/,1X,A,8(I3,2X)/,1X,A,2(I3,2X)/,1X,A,4(I3,2X)/,
	4        1X,A,2(I3,2X)/,1X,A,2(I3,2X)/,1X,A,2(I3,2X)/,
	5        1X,A,2(I3,2X)/,1X,A,4(I3,2X)/,
	5	 1X,A,8(I3,2X)/,1X,A,20(I3,2X)/,16X,20(I3,2X)/,
	6        1X,A,12(I3,2X)/,1X,A,1X,4(8A,2X))

 6021	FORMAT (/,1X,A,8(I3,2X)/,1X,A,6(I3,2X)/,1X,A,8(I3,2X)/,
	7        1X,A,2(I3,2X)/,1X,A,2(I3,2X)/,1X,A,24(I3,1X)/,
	8        16X,24(I3,1X)/,16X,26(I3,1X)/,1X,A,2(I3,2X)/,
	9        1X,A,2(I3,2X)/,1X,A,2(I3,2X))


	IF (STATUS .NE. 0) THEN
	  CALL LIB$SIGNAL ( FGA_WRITE_ERR, %VAL(1), %VAL(STATUS) )
	END IF

	RETURN
	END
