	integer * 4 function  fsl_display_model ()

c-------------------------------------------------------------------------------
c
c	Function FSL_DISPLAY_MODEL
c
c	This function plots the emissivities that comprise the Firas calibration
c	model solution.  The function also lists the values of the derived
c	bolometer parameters.
c
c	Author:  
c                FCF_Display_Model
c                Gene Eplee
c		 General Sciences Corp.
c		 14 July 1992
c       Author:  
c                FSL_Display_Model
c                Shirley M. Read
c                Hughes STX Corporation
c                July 1995
c
c-------------------------------------------------------------------------------
c
c	Input:
c		none
c
c	Output:
c		none
c
c	Subroutines called:
c		fut_plot
c		fut_plot_title
c		fut_setxaxl
c		lib$movc5
c		ots$cvt_ti_l
c		str$trim
c		str$upcase
c
c	Include files:
c		fsl_config.txt
c		fsl_invoc.txt
c		fsl_model.txt
c		fut_params.txt
c
c-------------------------------------------------------------------------------
c
c       Changes for FSL:
c
c       Shirley M. Read, Hughes STX Corporation, July 24, 1995 
c       Modified FCF_Display_Model to FSL_Display_Model for the new FIRAS 
c       pipeline which will process long spectra to get improved frequency 
c       resolution. An array of 32 real*8 bolometer parameters and arrays of
c       5 257 point complex*16 instrument emissivities comprise the calibration
c       model solution. 
c           1. Since model array sizes for the new pipeline are unchanged,the 
c              array sizes for the model are unchanged for FSL. However, the
c              frequency range for valid solutions varies with channel and
c              scan mode combination. In order to maximize the display features,
c              the last valid point in the external calibrator emissivity array
c              is used as the stop index for the plots.
c           2. Changed call to new FUT_Setxaxl to handle the longer spectra. 
c              Modified the calling sequence from old routine to new.
c
c-------------------------------------------------------------------------------

	implicit none

	include '(fut_params)'
	include '(fsl_config)'
	include '(fsl_invoc)'
	include '(fsl_model)'

	character *  16  answer			!  query response
	character *  16  dummy			!  dummy query response
	character *  60  label			!  coadd label
	character *  32  plot_device		!  plot device
	character * 100  plot_label		!  plot label
	character *  64	 plt_com_file		!  plt command file name
	character * 100  title(3)		!  plot title

	complex * 8	cemis(257)		!  data array for plotting

	integer * 4	fakeit			!  fakeit flag
	integer * 4	gain			!  commanded gain
	integer * 4	j			!  a counter
	integer * 4	k			!  a counter
	integer * 4	nans			!  number of answer
	integer * 4	numlen			!  position of number in answer
	integer * 4	plt_com			!  plt command flag
	integer * 4	status			!  return status
	integer * 4	sweeps			!  number of mtm sweeps
	integer * 4	upmode			!  microprocessor mode
	integer * 4	xcal_pos		!  xcal position flag
	integer * 4	zp			!  zero point flag
	integer * 4     npts                    !  number of points to plot
	integer * 4     scale1 / 1 /            !  spectral type of x axis scale
	integer * 4     first_sample / 1 /      !  first sample of ifg
	integer * 4     display_upmode / 4 /    !  microprocessor science mode

	real	* 4	spacex			!  tickmark spacing
	real	* 4	startx			!  starting tickmark

	integer * 4	fut_setxaxl
	integer * 4	ots$cvt_ti_l

	external	fsl_normal
	external	fut_normal

C
C  Initialize the routine.
C

c
c  Initialize the plot.
c
	zp           = fac_present
	label        = '  ' // model_ttag // '  ' // model_label 
	sweeps       = -1
	upmode       = -1
	xcal_pos     =  fac_xcalin
	fakeit       =  0
	gain         = -1
	plot_device  = fcc_plot_device
	plt_com      = fcc_plt_com
	plt_com_file = fcc_plt_com_file

c
c  Note:  In the following call to FUT_SETXAXL the microprocessor mode is hard
c	coded as 4.  This number is used by FUT_SETXAXL to initialize the x-axis
c	as optical path difference.  Since FSL_DISPLAY_MODEL only uses the
c	x-axis as wavenumbers, this hard-coded value has no effect on the plots
c	generated by this routine. The first sample is hard coded to 1. IFGs
c       which do not start with the first sample are not calibrated.
c
	status = fut_setxaxl (fcc_chan, fcc_smode, fakeit, display_upmode,
     .	                     fcc_ngroup, config.nyquist, scale1, first_sample, 
     .                       startx, spacex)
	if (status .ne. %loc(fut_normal)) then
	   fsl_display_model = status
	   return
	endif
	npts = stop_idx
c
c  Get the user input
c
	answer       = 'Y'
	do while (answer(1:1) .ne. 'Q')

	   type 10, model_label(1:mod_lablen)
  10	   format (/, 3x, 'Parameters for calibration model solution    ', a //,
     .		      3x, 'Choose what to view: ', /,
     .		      5x, '(1) Transfer function', /,
     .		      5x, '(2) Ical emissivity', /,
     .		      5x, '(3) Skyhorn emissivity', /,
     .		      5x, '(4) Refhorn emissivity', /,
     .		      5x, '(5) Dihedral emissivity', /,
     .		      5x, '(6) Structure emissivity', /,
     .		      5x, '(7) Bolometer emissivity', /,
     .		      5x, '(8) Bolometer Parameters', /,
     .		      5x, '(9) Quit displaying plots', /,
     .		      5x, '===> ', $)

	   accept 20, answer
  20	   format(a)

	   call str$trim (answer, answer, numlen)
	   call str$upcase (answer, answer)
	   status = ots$cvt_ti_l (answer(1:numlen), nans, %val(4), 1)
	   if (.not. status) then
	      nans = 0
	   endif
	   call lib$movc5 (0,,0,2056,cemis)	!  Initialize the data array.


C
C  Plot the optical model solution
C

	   if ((nans .eq. 1)  .or.  (answer(1:1) .eq. 'T')) then
c
c  Plot the transfer function.
c
	      do j = 1, 257
	         cemis(j) = cmplx(emiss(1,j))
	      enddo
	      plot_label = 'Optical Transfer Function'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Transfer Function',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 2)  .or.  (answer(1:1) .eq. 'I')) then
c
c  Plot the Ical emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(2,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Internal Calibrator Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 3)  .or.  (answer(1:1) .eq. 'S')) then
c
c  Plot the Skyhorn emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(3,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Sky Horn Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 4)  .or.  (answer(1:1) .eq. 'R')) then
c
c  Plot the Refhorn emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(4,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Reference Horn Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 5)  .or.  (answer(1:1) .eq. 'D')) then
c
c  Plot the Dihedral emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(5,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Dihedral Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 6)  .or.  (answer(1:2) .eq. 'ST')) then
c
c  Plot the Structure emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(6,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Structure Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 7)  .or.  (answer(1:1) .eq. 'B')) then
c
c  Plot the Bolometer emissivity.
c
	      do j = 1, 257
	         if (cdabs(emiss(1,j)) .le. trlim) then
	            cemis(j) = cmplx(0.0, 0.0)
	         else
	            cemis(j) = cmplx(emiss(7,j)/emiss(1,j))
	         endif
	      enddo
	      plot_label = 'Bolometer Emissivity'

	      call fut_plot_title (label, fcc_ngroup, sweeps, fcc_speed,
     .				   fcc_length, fcc_chan, upmode, xcal_pos,
     .				   fakeit, gain, plot_label, title)
	      call fut_plot (cemis, npts, startx, spacex, title,
     .			     'Wave Number (icm)', 'Emissivity',
     .			     zp, fac_present, plot_device,
     .			     plt_com, plt_com_file)


	   elseif ((nans .eq. 8)  .or.  (answer(1:1) .eq. 'BP')) then
c
c  Print the bolometer parameters.
c
	      type 30, label
  30	      format (//, 3x, 'Calibration model solution: ', /,
     .			  5x, a)
	      type 40, (bolparm(j), j=1,9), (param(k), k=10,20)
  40	      format (  3x, 'Derived bolometer parameters: ', /,
     .			5x, 'R0       Characteristic resistance:', 3x, G15.6, /,
     .			5x, 'T0      Characteristic temperature:', 3x, G15.6, /,
     .			5x, 'G1    Coeff of thermal conductance:', 3x, G15.6, /,
     .			5x, 'Beta  Index of thermal conductance:', 3x, G15.6, /,
     .			5x, 'Rho      Resistance due to E field:', 3x, G15.6, /,
     .			5x, 'C3       Cubic heat capacity coeff:', 3x, G15.6, /,
     .			5x, 'C1      Linear heat capacity coeff:', 3x, G15.6, /,
     .			5x, 'Jo                     JFET offset:', 3x, G15.6, /,
     .			5x, 'Jg                       JFET gain:', 3x, G15.6, /,
     .			5x, 'H3              3rd harmonic coeff:', 3x, G15.6, /,
     .			5x, 'H2              2nd harmonic coeff:', 3x, G15.6, /,
     .			5x, 'A        Ical temp drift amplitude:', 3x, G15.6, /,
     .			5x, 'B    Ical temp drift time constant:', 3x, G15.6, /,
     .			5x, 'C           Ical temp drift offset:', 3x, G15.6, /,
     .			5x, 'VS             Secondary vibration:', 3x, G15.6, /,
     .			5x, 'VP0              Primary vibration:', 3x, G15.6, /,
     .			5x, 'VP1       Primary Vibration linear:', 3x, G15.6, /,
     .			5x, 'VP2    Primary Vibration quadratic:', 3x, G15.6, /,
     .			5x, 'VP3        Primary Vibration cubic:', 3x, G15.6, /,
     .			5x, 'VP4      Primary Vibration quartic:', 3x, G15.6, /,
     .			5x, 'Hit return to continue ==> ', $)

	      accept 50, dummy
  50	      format(a)


	   elseif ((nans .eq. 9)  .or.  (answer(1:1) .eq. 'Q')) then
c
c  Exit the plot menu.
c
	      answer = 'Q'


	   else
c
c  Reply not recognized.
c
	      type 60
  60	      format (3x, 'Please try again.')


	   endif	!	(answer

	enddo		!	(while answer

	type 70
  70	format (/)


	fsl_display_model = %loc(fsl_normal)

	return
	end
