#!/bin/bash

# Node groups and associated data
list1=owl{17..24}.uio.no
list2=owl{25..28}.uio.no
list3=owl{29..30}.uio.no
list4=owl{31..35}.uio.no
list5=owl{36..37}.uio.no
list6=owl38.uio.no
list7=owl{40..46}.uio.no
list8=hyades{2..3}.uio.no
list9=hyades4.uio.no
list10=hyades5.uio.no
list11=hyades6.uio.no
list12=hyades{7..9}.uio.no
list13=hyades{10..16}.uio.no
lists=(list1 list2 list3 list4 list5 list6 list7 list8 list9 list10 list11)
ns=(24 72 64 64 128 192 192 86 64 24 64)
tLen=${#lists[@]}
builds=("owl1724" "owl2528" "owl2930" "owl3135" "owl3637" "owl38" "owl4046" "hya13" "hya4" "hya5" "hya6" "hya79" "hya1016")

# Environment setup
module purge

module load intel/oneapi compiler/latest mpi/latest mkl/latest
build=0
for (( i=0; i<${tLen}; i++ ));
do
  c=${!lists[$i]}
  v=$(eval "echo $c")
  if [[ "$v" == *"$HOSTNAME"* ]]
  then
    build=$((i+1))
    build=${builds[$i]}
    n=${ns[$i]}
  fi
done
echo $build

# Set the build directory (only update this one variable when needed), e.g. "/mn/stornext/u3/raelynsu/code/Commander/build_${build}_oneapi_Debug"
build_dir="/mn/stornext/u3/raelynsu/code/Commander/build_${build}_oneapi_Debug"
# Parameter file and output directory
pfile=param_HFI_test.txt
#Set the output directory, e.g. "/mn/stornext/d22/cmbco_nobackup/username/chains"
dir="/mn/stornext/d22/cmbco_nobackup/username/chains"

seed=$RANDOM

# Commander setup
killall -9 commander3
##set this to your defaults directory, e.g. "/mn/stornext/u3/raelynsu/code/Commander/commander3/parameter_files/defaults"
export COMMANDER_PARAMS_DEFAULT="/mn/stornext/u3/raelynsu/code/Commander/commander3/parameter_files/defaults"
export HEALPIX="$build_dir/install/healpix"
export LD_LIBRARY_PATH="$build_dir/install/lib:$build_dir/install/healpix/lib:$LD_LIBRARY_PATH"

cp $pfile $dir/${pfile}_orig_v1

# Run commander
export OMP_NUM_THREADS=1; mpirun -env I_MPI_FABRICS shm -n $n "$build_dir/install/bin/commander3" $pfile 2>&1| tee -a $dir/slurm.txt 


